[ids]
0001:0001

[main]
leftalt = layer(cmd)
leftmeta = layer(alt)
rightalt = layer(langsw)

[langsw]
space = M-space

[cmd:C]
left = home
right = end
up = C-home
down = C-end
backspace = C-S-backspace
l = M-l
q = M-q
t = M-t
r = M-r
1 = M-1
2 = M-2
3 = M-3
4 = M-4
5 = M-5
6 = M-6
7 = M-7
8 = M-8
9 = M-9
0 = M-0

[cmd+shift]
1 = M-S-1
2 = M-S-2
3 = M-S-3
4 = M-S-4
5 = M-S-5
6 = M-S-6
7 = M-S-7
8 = M-S-8
9 = M-S-9
0 = M-S-0
r = M-S-r

[alt]
left = C-left
right = C-right
backspace = C-backspace
delete = C-delete
